# Generated by Django 4.1.2 on 2022-11-03 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graphics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('discription', models.TextField()),
                ('media', models.FileField(upload_to='graphics/')),
                ('pub_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
