# Generated by Django 4.1.2 on 2022-11-03 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphics',
            name='cost',
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='graphics',
            name='discount',
            field=models.FloatField(max_length=4, null=True),
        ),
    ]
