# Generated by Django 4.1.2 on 2022-11-03 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_graphics_cost_alter_graphics_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphics',
            name='cost',
            field=models.FloatField(default=0.0, max_length=20),
        ),
        migrations.AlterField(
            model_name='graphics',
            name='discount',
            field=models.FloatField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='graphics',
            name='media',
            field=models.FileField(upload_to=''),
        ),
    ]
