# Generated by Django 4.1.2 on 2022-11-19 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_newsletter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
